
#OUTER JOIN 
SELECT * FROM customer;
SELECT * FROM orders;


-- 주문자 ID, 주문 상품명, 주문수량, 주문자명을 INNER JOIN

SELECT C.CUSTOMER_ID, PRODUCT_NAME, ORDER_CNT, NAME 
FROM customer C INNER JOIN orders O
ON C.CUSTOMER_ID = O.CUSTOMER_ID;


SELECT C.CUSTOMER_ID, ORDER_ID, PRODUCT_NAME, ORDER_CNT, NAME  
FROM customer C LEFT OUTER JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID;


SELECT C.CUSTOMER_ID, ORDER_ID, PRODUCT_NAME, ORDER_CNT, NAME  
FROM orders O RIGHT OUTER JOIN CUSTOMER C 
ON C.CUSTOMER_ID = O.CUSTOMER_ID;

# 주문자 ID = 5 가 CUSTOMER 테이블 밖에 없다. 



SELECT * FROM book_category;
SELECT * FROM book;

# BOOK_CATEGORY 테이블에 존재하는 모든 카테고리에 대한
# 카테고리 번호, 카테고리 이름, 책이름, 책 가격을 조회

SELECT B.CATE_CODE, CATE_NAME, BOOK_NAME, BOOK_PRICE 
FROM book B INNER JOIN book_category C
ON B.CATE_CODE = C.CATE_CODE;

SELECT B.CATE_CODE, CATE_NAME, BOOK_NAME, book_PRICE
FROM book_category C LEFT OUTER JOIN book B
ON B.CATE_CODE = C.CATE_CODE;












