CREATE TABLE SECURITY_MEMBER(
	MEM_EMAIL VARCHAR(100) PRIMARY KEY
	, MEM_PW VARCHAR(100) NOT NULL
	, MEM_NAME VARCHAR(100) NOT NULL
	, MEM_ROLE VARCHAR(30) NOT NULL
);

#암호화 때문에 비밀번호는 varchar(100)으로 설정 

SELECT * FROM SECURITY_MEMBER;
DELETE FROM SECURITY_MEMBER;
COMMIT;