-- 1번
SELECT STU_NUM AS '학생번호', STU_NAME AS '학생명', KOR_SCORE, ENG_SCORE FROM study_student
WHERE KOR_SCORE >=60 AND ENG_SCORE > 70;


-- 2번
SELECT * FROM study_student 
WHERE CLASS_NAME IN('디자인반','영상반')
AND HOBBY IS NOT NULL;


-- 3번
SELECT STU_NUM, STU_NAME, KOR_SCORE FROM study_student
WHERE STU_NAME LIKE '김%' AND KOR_SCORE BETWEEN 70 AND 85
ORDER BY STU_NUM DESC; 


-- 4번
SELECT STU_NUM, STU_NAME, CLASS_NAME, ENG_SCORE FROM study_student
WHERE HOBBY IS NOT NULL
ORDER BY CLASS_NAME ASC, ENG_SCORE DESC; 


-- 5번
SELECT * FROM study_student
WHERE KOR_SCORE + ENG_SCORE >= 170; 


-- 6번
SELECT STU_NUM, STU_NAME, KOR_SCORE, ENG_SCORE, (KOR_SCORE + ENG_SCORE) AS '총점' FROM study_student
-- WHERE CLASS_NAME != '영상반';
WHERE CLASS_NAME NOT IN('영상반'); 


-- 7번 
SELECT DISTINCT HOBBY FROM study_student 
WHERE HOBBY IS NOT NULL;




