# 각 테이블 수정하는 문법


#데이터 타입(자료형) 변경 
ALTER TABLE environment
MODIFY COLUMN TEMPERATURE FLOAT;

#  칼럼과 데이터 추가
ALTER TABLE ENVIRONMENT ADD COLUMN HUMIDITY FLOAT;

# 테이블 구조는 두고 데이터만 삭제team4(id값도 1부터 시작)
TRUNCATE TABLE  QNA_REPLY;


INSERT INTO 


DELETE FROM user;
DELETE FROM user;

ALTER TABLE USER AUTO_INCREMENT = 1;

COMMIT;

######################################################

UPDATE user SET
   USER_ROLE= 'ROLE_ADMIN'
   WHERE USER_EMAIL = 'ldy@naver.com';
COMMIT;


#칼럼명 변경하기 
ALTER TABLE crop_standards
CHANGE COLUMN id ID INT,
CHANGE COLUMN crop CROP VARCHAR(50),
CHANGE COLUMN temp_min TEMP_MIN FLOAT,
CHANGE COLUMN temp_max TEMP_MAX FLOAT,
CHANGE COLUMN humid_min HUMID_MIN FLOAT,
CHANGE COLUMN humid_max HUMID_MAX FLOAT,
CHANGE COLUMN soil_min SOIL_MIN FLOAT,
CHANGE COLUMN soil_max SOIL_MAX FLOAT,
CHANGE COLUMN lux_min LUX_MIN INT,
CHANGE COLUMN lux_max LUX_MAX INT,
CHANGE COLUMN adc_min ADC_MIN INT,
CHANGE COLUMN adc_max ADC_MAX INT;


#칼럼 추가하고 속성도 추가하기 
ALTER TABLE crop_standards
ADD COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

#이미지 칼럼 추가하고 데이터 타입  
ALTER TABLE crop_standards
ADD COLUMN IMG_NAME VARCHAR(100);



SELECT *
FROM LIKE_PLANT
WHERE (USER_EMAIL, BOARD_NUM) IN (
    SELECT USER_EMAIL, BOARD_NUM
    FROM LIKE_PLANT
    GROUP BY USER_EMAIL, BOARD_NUM
    HAVING COUNT(*) > 1
);


DELETE FROM LIKE_PLANT
WHERE (USER_EMAIL, BOARD_NUM, LIKE_NUM) NOT IN (
    SELECT USER_EMAIL, BOARD_NUM, MIN(LIKE_NUM)
    FROM LIKE_PLANT
    GROUP BY USER_EMAIL, BOARD_NUM
);
COMMIT;


ALTER TABLE LIKE_PLANT
ADD CONSTRAINT unique_like UNIQUE (USER_EMAIL, BOARD_NUM);


INSERT INTO USER (
    USER_EMAIL,
    USER_PASSWORD,
    USER_TEL,
    USER_ROLE,
    JOIN_DATE,
    USER_NAME
) VALUES (
    'cgj@naver.com',
    'aaa111',
    '010-2866-9999',
    'ROLE_ADMIN',
    NOW(),
    '조광진'
);



UPDATE qna_board SET QNA_NUM = 1 WHERE QNA_NUM = 24;
UPDATE qna_board SET QNA_NUM = 2 WHERE QNA_NUM = 30;
UPDATE qna_board SET QNA_NUM = 3 WHERE QNA_NUM = 32;
UPDATE qna_board SET QNA_NUM = 4 WHERE QNA_NUM = 33;
UPDATE qna_board SET QNA_NUM = 5 WHERE QNA_NUM = 34;
ALTER TABLE board_farmers AUTO_INCREMENT = 3;


UPDATE plant_story 
SET CONTENT = (SELECT CONTENT FROM plant_story WHERE BOARD_NUM = 37);

COMMIT;

