CREATE TABLE BOARD_REPLY (
 	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT
 	,CONTENT VARCHAR(30) NOT NULL
 	,WRITER VARCHAR(20) NOT NULL
 	,REG_DATE DATETIME DEFAULT SYSDATE()
 	,BOARD_NUM INT NOT NULL REFERENCES board(BOARD_NUM)
);

-- DB에서 시간 자료형은 2가지
-- DATETIME, TIMESTAMP
-- DATETIME은 우리나라 시간만
-- TIMESTAMP는 시차까지 포함  


INSERT INTO board_reply VALUES (
	1
	,'내용입니다'
	,'김자바'
	,NOW()
	,4
);

DELETE FROM board_reply
WHERE BOARD_NUM = 9;

SELECT * FROM board_reply;
COMMIT;
SELECT * FROM board;
