
#상품정보 테이블 
CREATE TABLE SHOP_ITEM(
	ITEM_CODE INT PRIMARY KEY AUTO_INCREMENT
	,ITEM_NAME VARCHAR(10)
	,ITEM_PRICE INT 
	,ITEM_INTRO VARCHAR(20)
	,REG_DATA DATETIME DEFAULT SYSDATE() 	
);

COMMIT;
ROLLBACK;

SELECT * FROM SHOP_ITEM;

SELECT ITEM_CODE, ITEM_NAME, ITEM_PRICE, REG_DATA
FROM shop_item;

