#회원정보

CREATE TABLE REST_member (
	MAN_ID VARCHAR(20) PRIMARY KEY
	,MAN_NAME VARCHAR(10) NOT NULL
	,MAN_AGE INT DEFAULT 0
	,MAN_TEL VARCHAR(30) UNIQUE
); 

# 회원정보 조회 = > getmapping

SELECT * FROM REST_MEMBER;


INSERT INTO REST_MEMBER VALUES('AAA','KIM',20,'010-1111-1111'); 
INSERT INTO REST_MEMBER VALUES('BBB','LEE',30,'010-1111-2222'); 
INSERT INTO REST_MEMBER VALUES('CCC','HONG',40,'010-1111-3333'); 


COMMIT;

SELECT *
FROM REST_MEMBER
WHERE MAN_ID = 'AAA';


SELECT * 
FROM rest_member
WHERE MAN_ID ='AAA'
AND MAN_AGE = 20;


#회원정보 등록 => postMapping 

INSERT INTO rest_member(MAN_ID, MAN_NAME, MAN_AGE, MAN_TEL) 
VALUES('DDD','PARK',50,'010');


#회원 한명을 삭제하기

DELETE FROM rest_member
WHERE MAN_ID = 'AAA';


#회원 한명의 이름과 나이를 수정하기

UPDATE rest_member 
SET 
MAN_NAME ='TTT',
MAN_AGE = 35
WHERE MAN_ID = 'AAA';




# 실습 게시글  정보 테이블  

CREATE TABLE REST_BOARD(
	BOARD_NUM INT PRIMARY KEY,
	TITLE VARCHAR(10) NOT NULL,
	CONTENT VARCHAR(20),
	WRITER VARCHAR(10)
); 

INSERT INTO REST_BOARD VALUES(1,'제목1','내용1','KIM');
INSERT INTO REST_BOARD VALUES(2,'제목2','내용2','KIM');
INSERT INTO REST_BOARD VALUES(3,'제목3','내용3','KIM');

COMMIT;

SELECT * FROM REST_BOARD;

SELECT * FROM REST_BOARD
WHERE BOARD_NUM = 1;





# 실습 상품정보 테이블 

CREATE TABLE REST_ITEM(
	ITEM_CODE INT PRIMARY KEY AUTO_INCREMENT,
	ITEM_NAME VARCHAR(20) NOT NULL,
	ITEM_PRICE INT,
	ITEM_COLOR VARCHAR(10)
);


INSERT INTO REST_ITEM (ITEM_NAME, ITEM_PRICE, ITEM_COLOR) 
VALUES ('청바지',30000,'파란색');


DELETE FROM REST_ITEM 
WHERE ITEM_CODE = 12;


UPDATE REST_ITEM  
SET 
ITEM_NAME = '사과', 
ITEM_PRICE = 20000,
ITEM_COLOR = '검정'
WHERE
ITEM_CODE = 12;


SELECT * FROM REST_ITEM;

ROLLBACK;
 

