#상품 정보 테이블
CREATE TABLE ITEM_INFO(
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	,ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	,ITEM_PRICE INT NOT NULL 
	,SELLER VARCHAR(10)
	,ITEM_INTRO VARCHAR(20)
	,REG_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM ITEM_INFO;
COMMIT;

DELETE FROM ITEM_INFO
WHERE ITEM_NUM = 54;

DROP TABLE order_info;

#주문 정보 테이블
CREATE TABLE order_info(
	ORDER_NUM INT PRIMARY KEY AUTO_INCREMENT
	,ITEM_NUM INT NOT NULL REFERENCES ITEM_INFO (ITEM_NUM)
	,BUYER VARCHAR(20) NOT NULL
	,BUY_CNT INT NOT NULL
	,BUY_PRICE INT NOT NULL
	,BUY_DATE DATETIME DEFAULT SYSDATE() 
); 

SELECT * FROM order_info;

SELECT ITEM_NAME, ITEM_PRICE, BUY_CNT, BUY_PRICE, BUYER, BUY_DATE
FROM item_info I INNER JOIN order_info O
ON I.ITEM_NUM = O.ITEM_NUM;



SELECT * FROM emp;
DESC emp;
SELECT * FROM dept;
DESC dept;

SELECT EMPNO, ENAME, SAL, E.DEPTNO, DNAME, LOC
FROM emp E INNER JOIN dept D
ON E.DEPTNO = D.DEPTNO; 

SELECT * FROM board;
SELECT * FROM board_reply;

# BOARD+REPLY 테이블의 컬럼 변경 
ALTER TABLE board_reply CHANGE COLUMN CONTENT REPLY_CONTENT VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN WRITER REPLY_WRITER VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN REPLY_REG_DATE REPLY_REG_DATE DATETIME DEFAULT SYSDATE();

# 모든 게시글의 게시글 번호, 제목, 작성자 및 게시글에 달린 댓글내용, 댓글작성자를 조화
SELECT B.BOARD_NUM, TITLE, WRITER, REPLY_CONTENT, REPLY_WRITER
FROM board B INNER JOIN board_reply R
ON B.BOARD_NUM = R.BOARD_NUM;

DESC board;
DESC board_reply;
DESC order_info;






